/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.80
 * Generated at: 2023-09-24 19:39:59 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.dao.MessageDao;

public final class admin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.dao.MessageDao");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

	String value = (String)session.getAttribute("login");
	if(value == null){
		response.sendRedirect("login.jsp");
		return;
	}

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("	<link rel=\"apple-touch-icon\" sizes=\"180x180\" href=\"./favicon/apple-touch-icon.png\">\r\n");
      out.write("    <link rel=\"icon\" type=\"image/png\" sizes=\"32x32\" href=\"./favicon/favicon-32x32.png\">\r\n");
      out.write("	<link rel=\"icon\" type=\"image/png\" sizes=\"16x16\" href=\"./favicon/favicon-16x16.png\">\r\n");
      out.write("	<link rel=\"manifest\" href=\"./favicon/android-chrome-512x512.png\">\r\n");
      out.write("	<link rel=\"mask-icon\" href=\"./favicon/safari-pinned-tab.svg\" color=\"#5bbad5\">\r\n");
      out.write("	<meta name=\"msapplication-TileColor\" content=\"#da532c\">\r\n");
      out.write("	<meta name=\"theme-color\" content=\"#ffffff\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <title>Admin Panel</title>\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <style type=\"text/css\">\r\n");
      out.write("        body {\r\n");
      out.write("            margin-top: 20px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .shadow {\r\n");
      out.write("            box-shadow: 0 0 3px rgb(53 64 78 / 20%) !important;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .rounded {\r\n");
      out.write("            border-radius: 5px !important;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .bg-light {\r\n");
      out.write("            background-color: #f7f8fa !important;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .bg-primary,\r\n");
      out.write("        .btn-primary,\r\n");
      out.write("        .btn-outline-primary:hover,\r\n");
      out.write("        .btn-outline-primary:focus,\r\n");
      out.write("        .btn-outline-primary:active,\r\n");
      out.write("        .btn-outline-primary.active,\r\n");
      out.write("        .btn-outline-primary.focus,\r\n");
      out.write("        .btn-outline-primary:not(:disabled):not(.disabled):active,\r\n");
      out.write("        .badge-primary,\r\n");
      out.write("        .nav-pills .nav-link.active,\r\n");
      out.write("        .pagination .active a,\r\n");
      out.write("        .custom-control-input:checked~.custom-control-label:before,\r\n");
      out.write("        #preloader #status .spinner>div,\r\n");
      out.write("        .social-icon li a:hover,\r\n");
      out.write("        .back-to-top:hover,\r\n");
      out.write("        .back-to-home a,\r\n");
      out.write("        ::selection,\r\n");
      out.write("        #topnav .navbar-toggle.open span:hover,\r\n");
      out.write("        .owl-theme .owl-dots .owl-dot.active span,\r\n");
      out.write("        .owl-theme .owl-dots.clickable .owl-dot:hover span,\r\n");
      out.write("        .watch-video a .play-icon-circle,\r\n");
      out.write("        .sidebar .widget .tagcloud>a:hover,\r\n");
      out.write("        .flatpickr-day.selected,\r\n");
      out.write("        .flatpickr-day.selected:hover,\r\n");
      out.write("        .tns-nav button.tns-nav-active,\r\n");
      out.write("        .form-check-input.form-check-input:checked {\r\n");
      out.write("            background-color: #6dc77a !important;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .badge {\r\n");
      out.write("            padding: 5px 8px;\r\n");
      out.write("            border-radius: 3px;\r\n");
      out.write("            letter-spacing: 0.5px;\r\n");
      out.write("            font-size: 12px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn-primary,\r\n");
      out.write("        .btn-outline-primary:hover,\r\n");
      out.write("        .btn-outline-primary:focus,\r\n");
      out.write("        .btn-outline-primary:active,\r\n");
      out.write("        .btn-outline-primary.active,\r\n");
      out.write("        .btn-outline-primary.focus,\r\n");
      out.write("        .btn-outline-primary:not(:disabled):not(.disabled):active {\r\n");
      out.write("            box-shadow: 0 3px 7px rgb(109 199 122 / 50%) !important;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn-primary,\r\n");
      out.write("        .btn-outline-primary,\r\n");
      out.write("        .btn-outline-primary:hover,\r\n");
      out.write("        .btn-outline-primary:focus,\r\n");
      out.write("        .btn-outline-primary:active,\r\n");
      out.write("        .btn-outline-primary.active,\r\n");
      out.write("        .btn-outline-primary.focus,\r\n");
      out.write("        .btn-outline-primary:not(:disabled):not(.disabled):active,\r\n");
      out.write("        .bg-soft-primary .border,\r\n");
      out.write("        .alert-primary,\r\n");
      out.write("        .alert-outline-primary,\r\n");
      out.write("        .badge-outline-primary,\r\n");
      out.write("        .nav-pills .nav-link.active,\r\n");
      out.write("        .pagination .active a,\r\n");
      out.write("        .form-group .form-control:focus,\r\n");
      out.write("        .form-group .form-control.active,\r\n");
      out.write("        .custom-control-input:checked~.custom-control-label:before,\r\n");
      out.write("        .custom-control-input:focus~.custom-control-label::before,\r\n");
      out.write("        .form-control:focus,\r\n");
      out.write("        .social-icon li a:hover,\r\n");
      out.write("        #topnav .has-submenu.active.active .menu-arrow,\r\n");
      out.write("        #topnav.scroll .navigation-menu>li:hover>.menu-arrow,\r\n");
      out.write("        #topnav.scroll .navigation-menu>li.active>.menu-arrow,\r\n");
      out.write("        #topnav .navigation-menu>li:hover>.menu-arrow,\r\n");
      out.write("        .flatpickr-day.selected,\r\n");
      out.write("        .flatpickr-day.selected:hover,\r\n");
      out.write("        .form-check-input:focus,\r\n");
      out.write("        .form-check-input.form-check-input:checked,\r\n");
      out.write("        .container-filter li.active,\r\n");
      out.write("        .container-filter li:hover {\r\n");
      out.write("            border-color: #6dc77a !important;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .bg-primary,\r\n");
      out.write("        .btn-primary,\r\n");
      out.write("        .btn-outline-primary:hover,\r\n");
      out.write("        .btn-outline-primary:focus,\r\n");
      out.write("        .btn-outline-primary:active,\r\n");
      out.write("        .btn-outline-primary.active,\r\n");
      out.write("        .btn-outline-primary.focus,\r\n");
      out.write("        .btn-outline-primary:not(:disabled):not(.disabled):active,\r\n");
      out.write("        .badge-primary,\r\n");
      out.write("        .nav-pills .nav-link.active,\r\n");
      out.write("        .pagination .active a,\r\n");
      out.write("        .custom-control-input:checked~.custom-control-label:before,\r\n");
      out.write("        #preloader #status .spinner>div,\r\n");
      out.write("        .social-icon li a:hover,\r\n");
      out.write("        .back-to-top:hover,\r\n");
      out.write("        .back-to-home a,\r\n");
      out.write("        ::selection,\r\n");
      out.write("        #topnav .navbar-toggle.open span:hover,\r\n");
      out.write("        .owl-theme .owl-dots .owl-dot.active span,\r\n");
      out.write("        .owl-theme .owl-dots.clickable .owl-dot:hover span,\r\n");
      out.write("        .watch-video a .play-icon-circle,\r\n");
      out.write("        .sidebar .widget .tagcloud>a:hover,\r\n");
      out.write("        .flatpickr-day.selected,\r\n");
      out.write("        .flatpickr-day.selected:hover,\r\n");
      out.write("        .tns-nav button.tns-nav-active,\r\n");
      out.write("        .form-check-input.form-check-input:checked {\r\n");
      out.write("            background-color: #6dc77a !important;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn {\r\n");
      out.write("            padding: 8px 20px;\r\n");
      out.write("            outline: none;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            font-size: 16px;\r\n");
      out.write("            letter-spacing: 0.5px;\r\n");
      out.write("            transition: all 0.3s;\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("            border-radius: 5px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        button:hover{\r\n");
      out.write("        	color:white  !important;\r\n");
      out.write("        	background-color: red  !important;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        #readMsg-hover:hover{\r\n");
      out.write("        	background-color: green !important;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("\r\n");
      out.write("        .btn-primary {\r\n");
      out.write("            background-color: #6dc77a !important;\r\n");
      out.write("            border: 1px solid #6dc77a !important;\r\n");
      out.write("            color: #fff !important;\r\n");
      out.write("            box-shadow: 0 3px 7px rgb(109 199 122 / 50%);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        a {\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("    <link href=\"https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css\" rel=\"stylesheet\" />\r\n");
      out.write("    <div class=\"container mt-5 pt-4\">\r\n");
      out.write("        <div class=\"row align-items-end mb-4 pb-2\">\r\n");
      out.write("            <div class=\"col-md-8\">\r\n");
      out.write("                <div class=\"section-title text-center text-md-start\">\r\n");
      out.write("                    <h4 class=\"title mb-4\">ADMIM PANEL</h4>\r\n");
      out.write("                    <p class=\"text-muted mb-0 para-desc\">An admin panel, short for administrative panel,\r\n");
      out.write("                         is a web-based or software interface that provides authorized individuals \r\n");
      out.write("                         or administrators with the tools and functionalities to manage, monitor, and\r\n");
      out.write("                          control various aspects of a system, application, or website. </p>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"row\"> \r\n");
      out.write("            <div class=\"col-lg-4 col-md-6 col-12 mt-4 pt-2\">\r\n");
      out.write("                <div class=\"card border-0 bg-light rounded shadow\">\r\n");
      out.write("                    <div class=\"card-body p-4\">\r\n");
      out.write("                    ");
int count = new MessageDao().contactCount(); 
      out.write("\r\n");
      out.write("                        <span class=\"badge rounded-pill bg-primary float-md-end mb-3 mb-sm-0\">");
      out.print(count );
      out.write(" CONTACTS</span>\r\n");
      out.write("                        <h5>Contact List</h5>\r\n");
      out.write("                        <div class=\"mt-3\">\r\n");
      out.write("                            <span class=\"text-muted d-block\"><i class=\"fa fa-home\" aria-hidden=\"true\"></i> <a href=\"#\"\r\n");
      out.write("                                    target=\"_blank\" class=\"text-muted\">ABHIJEET SHENDE</a></span>\r\n");
      out.write("                            <span class=\"text-muted d-block\"><i class=\"fa fa-map-marker\" aria-hidden=\"true\"></i>\r\n");
      out.write("                                INDIA</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"mt-3\">\r\n");
      out.write("                            <a href=\"read-message.jsp\" class=\"btn btn-primary\" id=\"readMsg-hover\">Read Message</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div style=\"text-align: center;padding-top: 50px;\" class=\"mt-3\">\r\n");
      out.write("            \r\n");
      out.write("            	\r\n");
      out.write("                <form action=\"Auth\" method=\"post\">\r\n");
      out.write("                <input type=\"hidden\" name=\"check\" value=\"Logout\">\r\n");
      out.write("                    <button class=\"btn btn-primary\" id=\"hover\">LOGOUT</button>\r\n");
      out.write("                </form>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    <script>\r\n");
      out.write("    \r\n");
      out.write("      \r\n");
      out.write("    \r\n");
      out.write("</script>\r\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-1.10.2.min.js\"></script>\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
