/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.80
 * Generated at: 2023-09-24 19:40:00 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/message.jsp", Long.valueOf(1693678687586L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<link rel=\"apple-touch-icon\" sizes=\"180x180\" href=\"./favicon/apple-touch-icon.png\">\r\n");
      out.write("    <link rel=\"icon\" type=\"image/png\" sizes=\"32x32\" href=\"./favicon/favicon-32x32.png\">\r\n");
      out.write("	<link rel=\"icon\" type=\"image/png\" sizes=\"16x16\" href=\"./favicon/favicon-16x16.png\">\r\n");
      out.write("	<link rel=\"manifest\" href=\"./favicon/android-chrome-512x512.png\">\r\n");
      out.write("	<link rel=\"mask-icon\" href=\"./favicon/safari-pinned-tab.svg\" color=\"#5bbad5\">\r\n");
      out.write("	<meta name=\"msapplication-TileColor\" content=\"#da532c\">\r\n");
      out.write("	<meta name=\"theme-color\" content=\"#ffffff\">\r\n");
      out.write("\r\n");
      out.write("	<meta charset=\"utf-8\">\r\n");
      out.write("	<link href=\"../changeCredential.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write("	<title>Login Page</title>\r\n");
      out.write("	<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap@4.5.0/dist/css/bootstrap.min.css\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("body {\r\n");
      out.write("	margin-top: 20px;\r\n");
      out.write("	background: #f6f9fc;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".account-block {\r\n");
      out.write("	padding: 0;\r\n");
      out.write("	background-image: url(https://bootdey.com/img/Content/bg1.jpg);\r\n");
      out.write("	background-repeat: no-repeat;\r\n");
      out.write("	background-size: cover;\r\n");
      out.write("	height: 100%;\r\n");
      out.write("	position: relative;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".account-block .overlay {\r\n");
      out.write("	-webkit-box-flex: 1;\r\n");
      out.write("	-ms-flex: 1;\r\n");
      out.write("	flex: 1;\r\n");
      out.write("	position: absolute;\r\n");
      out.write("	top: 0;\r\n");
      out.write("	bottom: 0;\r\n");
      out.write("	left: 0;\r\n");
      out.write("	right: 0;\r\n");
      out.write("	background-color: rgba(0, 0, 0, 0.4);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".account-block .account-testimonial {\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	color: #fff;\r\n");
      out.write("	position: absolute;\r\n");
      out.write("	margin: 0 auto;\r\n");
      out.write("	padding: 0 1.75rem;\r\n");
      out.write("	bottom: 3rem;\r\n");
      out.write("	left: 0;\r\n");
      out.write("	right: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".text-theme {\r\n");
      out.write("	color: #5369f8 !important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn-theme {\r\n");
      out.write("	background-color: #5369f8;\r\n");
      out.write("	border-color: #5369f8;\r\n");
      out.write("	color: #fff;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("*{box-sizing: border-box;}\r\n");
      out.write("\r\n");
      out.write("/* Button used to open the contact form - fixed at the bottom of the page */\r\n");
      out.write(".open-button {\r\n");
      out.write("  \r\n");
      out.write("  background-color: #555;\r\n");
      out.write("  color: white;\r\n");
      out.write("  padding: 12px 20px;\r\n");
      out.write("  border: none;\r\n");
      out.write("  cursor: pointer;\r\n");
      out.write("  opacity: 0.8;\r\n");
      out.write("  bottom: 30px;\r\n");
      out.write("  margin-right: auto;\r\n");
      out.write("  margin-left: auot;\r\n");
      out.write("  margin-bottom: 30px;\r\n");
      out.write("  margin-top:10px; \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* The popup form - hidden by default */\r\n");
      out.write(".form-popup {\r\n");
      out.write("  display: none;\r\n");
      out.write("  position: fixed;\r\n");
      out.write("  bottom: 0;\r\n");
      out.write("  left:-0.3%;\r\n");
      out.write("  bottom:18%;\r\n");
      out.write("  border: 3px solid #f1f1f1;\r\n");
      out.write("  z-index: 9;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Add styles to the form container */\r\n");
      out.write(".form-container {\r\n");
      out.write("  max-width: 300px;\r\n");
      out.write("  padding: 10px;\r\n");
      out.write("  background-color: white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Full-width input fields */\r\n");
      out.write(".form-container input[type=text], .form-container input[type=password] {\r\n");
      out.write("  width: 100%;\r\n");
      out.write("  padding: 15px;\r\n");
      out.write("  margin: 5px 0 22px 0;\r\n");
      out.write("  border: none;\r\n");
      out.write("  background: #f1f1f1;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* When the inputs get focus, do something */\r\n");
      out.write(".form-container input[type=text]:focus, .form-container input[type=password]:focus {\r\n");
      out.write("  background-color: #ddd;\r\n");
      out.write("  outline: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Set a style for the submit/login button */\r\n");
      out.write(".form-container .btn {\r\n");
      out.write("  background-color: #04AA6D;\r\n");
      out.write("  color: white;\r\n");
      out.write("  padding: 16px 20px;\r\n");
      out.write("  border: none;\r\n");
      out.write("  cursor: pointer;\r\n");
      out.write("  width: 100%;\r\n");
      out.write("  margin-bottom:10px;\r\n");
      out.write("  opacity: 0.8;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Add a red background color to the cancel button */\r\n");
      out.write(".form-container .cancel {\r\n");
      out.write("  background-color: red;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Add some hover effects to buttons */\r\n");
      out.write(".form-container .btn:hover, .open-button:hover {\r\n");
      out.write("  opacity: 1;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<div id=\"main-wrapper\" class=\"container\">\r\n");
      out.write("		<div class=\"row justify-content-center\">\r\n");
      out.write("			<div class=\"col-xl-10\">\r\n");
      out.write("				<div class=\"card border-0\">\r\n");
      out.write("					<div class=\"card-body p-0\">\r\n");
      out.write("						<div class=\"row no-gutters\">\r\n");
      out.write("							<div class=\"col-lg-6\">\r\n");
      out.write("								<div class=\"p-5\">\r\n");
      out.write("									<div class=\"mb-5\">\r\n");
      out.write("										<h3 class=\"h4 font-weight-bold text-theme\">Login</h3>\r\n");
      out.write("									</div>\r\n");
      out.write("									<h6 class=\"h5 mb-0\">Welcome back!</h6>\r\n");
      out.write("									<p class=\"text-muted mt-2 mb-5\">Enter your email address\r\n");
      out.write("										and password to access admin panel.</p>\r\n");
      out.write("										");
 
  	String msg = (String)session.getAttribute("msg");
  	if(msg != null)
  	{	
  		if(msg.equals("Data Send Sucessfully"))
  		{
  	
      out.write("\r\n");
      out.write("  			<h2 style=\"text-align:center; color:blue\">");
      out.print(msg);
      out.write("</h2>\r\n");
      out.write("  			 <meta http-equiv=\"refresh\" content=\"1\">\r\n");
      out.write("  	");

  		}
  		else{
  	
      out.write("\r\n");
      out.write("  			<h2 style=\"text-align:center; color:red\">");
      out.print(msg);
      out.write("</h2>\r\n");
      out.write("  			<meta http-equiv=\"refresh\" content=\"1\">\r\n");
      out.write("  		\r\n");
      out.write("  	 ");

  		}
  	}
  		session.removeAttribute("msg");
  	 
      out.write("\r\n");
      out.write("										\r\n");
      out.write("									<form action=\"Auth\" method=\"post\">\r\n");
      out.write("										<div class=\"form-group\">\r\n");
      out.write("										\r\n");
      out.write("											<label for=\"exampleInputEmail1\">Username</label> <input\r\n");
      out.write("												type=\"text\" class=\"form-control\" id=\"exampleInputEmail1\" placeholder=\"Enter Username\" name=\"username\">\r\n");
      out.write("										</div>\r\n");
      out.write("										<div class=\"form-group mb-5\">\r\n");
      out.write("											<label for=\"exampleInputPassword1\">Password</label> <input\r\n");
      out.write("												type=\"password\" class=\"form-control\"\r\n");
      out.write("												id=\"exampleInputPassword1\" placeholder=\"Enter Password\" name=\"password\">\r\n");
      out.write("										</div>\r\n");
      out.write("										<button type=\"submit\" class=\"btn btn-theme\">Login</button>\r\n");
      out.write("									</form>\r\n");
      out.write("									<button  class=\"open-button\" onclick=\"openForm()\">CHANGE CREDENTIALS</button>   \r\n");
      out.write("			\r\n");
      out.write("\r\n");
      out.write("				<!-- The form -->\r\n");
      out.write("				<div class=\"form-popup\" id=\"myForm\">\r\n");
      out.write("				<form action=\"Auth\" method=\"post\" class=\"form-container\">\r\n");
      out.write("				<h1>Login</h1>\r\n");
      out.write("			\r\n");
      out.write("				<label for=\"email\"><b>Old Password</b></label>\r\n");
      out.write("				<input type=\"text\" placeholder=\"Enter old password\" name=\"opass\" required>\r\n");
      out.write("			\r\n");
      out.write("				<label for=\"psw\"><b>New Password</b></label>\r\n");
      out.write("				<input type=\"password\" placeholder=\"Enter Password\" name=\"npass\" required>\r\n");
      out.write("			    \r\n");
      out.write("				<label for=\"psw\"><b>Confirm Password</b></label>\r\n");
      out.write("				<input type=\"password\" placeholder=\"Enter Confirm Password\" name=\"cpass\" required>\r\n");
      out.write("			    \r\n");
      out.write("				<input type=\"hidden\" name=\"check\" value=\"change\" >\r\n");
      out.write("			\r\n");
      out.write("				<button type=\"submit\" class=\"btn\">Update</button>\r\n");
      out.write("				<button type=\"button\" class=\"btn cancel\" onclick=\"closeForm()\">Close</button>\r\n");
      out.write("				</form>\r\n");
      out.write("				</div>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"col-lg-6 d-none d-lg-inline-block\">\r\n");
      out.write("								<div class=\"account-block rounded-right\">\r\n");
      out.write("									<div class=\"overlay rounded-right\"></div>\r\n");
      out.write("									<div class=\"account-testimonial\">\r\n");
      out.write("										\r\n");
      out.write("										<h4 class=\"text-white mb-4\">Believe Yourself!</h4>\r\n");
      out.write("										<p class=\"lead text-white\">\"Make the Dream Break the Body!! Achieve Distance Zero, \r\n");
      out.write("										So you get the Meaning of Life\"</p>\r\n");
      out.write("										<p>- Admin User</p>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("	<script src=\"https://code.jquery.com/jquery-1.10.2.min.js\"></script>\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"https://cdn.jsdelivr.net/npm/bootstrap@4.5.0/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("	<script type=\"text/javascript\">\r\n");
      out.write("		\r\n");
      out.write("	</script>\r\n");
      out.write("	\r\n");
      out.write("	<script>\r\n");
      out.write("    \r\n");
      out.write("       function openForm() {\r\n");
      out.write("    	  document.getElementById(\"myForm\").style.display = \"block\";\r\n");
      out.write("    	}\r\n");
      out.write("\r\n");
      out.write("    	function closeForm() {\r\n");
      out.write("    	  document.getElementById(\"myForm\").style.display = \"none\";\r\n");
      out.write("    	}\r\n");
      out.write("    \r\n");
      out.write("</script>\r\n");
      out.write("	\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
